[package]
name = "pathfinder-perf-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
tokio = { version = "1.19.2", features = ["full"] }
url = "2.2.2"
